services:
  mysql:
    image: mysql:8.0
    container_name: enrollment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: enrollment1234
      MYSQL_DATABASE: course_registration
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-penrollment1234" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: enrollment-app

    depends_on:
      mysql:
          condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data: